# Generated by Django 3.2 on 2021-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=200)),
                ('country_origin', models.CharField(max_length=200)),
                ('conservation_status', models.CharField(max_length=200)),
                ('distribution', models.CharField(max_length=500)),
                ('used_for', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('skin_color', models.CharField(max_length=200)),
                ('coat', models.CharField(max_length=200)),
                ('horn_status', models.CharField(max_length=200)),
                ('characteristics', models.CharField(max_length=10000)),
                ('history', models.CharField(max_length=10000)),
            ],
        ),
    ]
