# Generated by Django 3.2 on 2021-05-18 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210518_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='food',
        ),
        migrations.AddField(
            model_name='cat',
            name='height',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='weight',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
