# Generated by Django 3.2 on 2021-06-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20210527_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='comment_id',
        ),
    ]
