# Generated by Django 3.2 on 2021-06-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_cat_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cat'),
        ),
    ]
